###  REST Client (extenção do VS code)
###  https://www.npmjs.com/package/json-server

###  GET full

http://localhost:3000/cursos

###  GET de um curso expecífico

GET http://localhost:3000/cursos/1

###  POST

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

{
    "name": "typescript"
}

###  PUT

PUT http://localhost:3000/cursos/2 HTTP/1.1
content-type: application/json

{
    "name": "java oo"
}


###  DELETE

DELETE http://localhost:3000/cursos/2
